<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { deleteStudent, getStudents, getSystemStats } from '../api'

const students = ref([]); const stats = ref(null); const query = ref(''); const error = ref(''); const busy = ref('')
const router = useRouter()
let timer
async function refresh() {
  try { [students.value, stats.value] = await Promise.all([getStudents(query.value), getSystemStats()]); error.value = '' }
  catch (err) { error.value = err.message }
}
function imageUrl(student) { return student.image_url ? `${import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000'}${student.image_url}` : '' }
function chooseUpdate(student) { router.push({ name: 'register', query: { update: student.student_id } }) }
async function remove(student) { if (!confirm(`Delete ${student.name} (${student.student_id}) permanently?`)) return; busy.value=student.student_id
  try { await deleteStudent(student.student_id); await refresh() } catch (err) { error.value=err.message } finally { busy.value='' } }
onMounted(async()=>{ await refresh(); timer=window.setInterval(refresh, 4000) }); onBeforeUnmount(()=>clearInterval(timer))
</script>
<template>
  <div class="page"><div class="intro"><p class="eyebrow">Operations</p><h1>Student management</h1><p class="lede">Live enrollment inventory, recognition infrastructure, and safe face lifecycle controls.</p></div>
    <p v-if="error" class="feedback error">{{ error }}</p>
    <section v-if="stats" class="stats"><div><span>FAISS</span><strong>{{ stats.faiss.backend.toUpperCase() }}</strong></div><div><span>Vectors</span><strong>{{ stats.faiss.vector_count.toLocaleString() }}</strong></div><div><span>Index size</span><strong>{{ (stats.faiss.index_size_bytes / 1048576).toFixed(1) }} MB</strong></div><div><span>CPU / RAM</span><strong>{{ stats.cpu_percent }}% / {{ stats.ram_used_mb }} MB</strong></div><div><span>GPU</span><strong>{{ stats.gpu.available ? `${stats.gpu.name} · ${stats.gpu.utilization_percent}%` : 'Unavailable' }}</strong></div><div><span>Auth p95</span><strong>{{ stats.recognition_latency_ms.p95 ?? '—' }} ms</strong></div></section>
    <section v-if="stats" class="model-performance"><div class="section-heading"><div><p class="eyebrow">Model telemetry</p><h2>Inference performance and load footprint</h2></div><small>Rolling window: last 500 calls. CUDA timings are synchronized when the CUDA runtime is available.</small></div>
      <div class="performance-summary"><span>Model inference <strong>{{ stats.performance_summary?.model_inference.average_model_inference_latency_ms ?? '—' }} ms</strong></span><span>FAISS search <strong>{{ stats.performance_summary?.faiss_search_latency_ms.average ?? '—' }} ms</strong></span><span>End-to-end auth <strong>{{ stats.performance_summary?.end_to_end_authentication_latency_ms.average ?? '—' }} ms</strong></span></div>
      <div class="table-wrap"><table><thead><tr><th>Model</th><th>Stage</th><th>Calls</th><th>Avg</th><th>P50</th><th>P95</th><th>P99</th><th>Min</th><th>Max</th><th>Device</th><th>Load time</th><th>VRAM Δ</th></tr></thead><tbody><tr v-for="model in stats.models" :key="model.name"><td><strong>{{ model.name }}</strong><small>{{ model.active ? 'Active' : 'Previously loaded' }}<template v-if="model.load?.shared_bundle"> · shared bundle</template></small></td><td>{{ model.stage }}</td><td>{{ model.inference_count }}</td><td>{{ model.average_latency_ms ?? '—' }} ms</td><td>{{ model.p50_latency_ms ?? '—' }} ms</td><td>{{ model.p95_latency_ms ?? '—' }} ms</td><td>{{ model.p99_latency_ms ?? '—' }} ms</td><td>{{ model.min_latency_ms ?? '—' }} ms</td><td>{{ model.max_latency_ms ?? '—' }} ms</td><td>{{ model.information?.device ?? '—' }}</td><td>{{ model.load?.load_latency_ms ?? '—' }} ms</td><td>{{ model.load?.device_vram_delta_mb ?? '—' }} MB</td></tr><tr v-if="!stats.models?.length"><td colspan="12">No model telemetry is available yet.</td></tr></tbody></table></div>
      <details class="model-info"><summary>Model information</summary><div v-for="model in stats.models?.filter((item) => item.information?.model_type && !item.load?.shared_bundle)" :key="`${model.name}-info`" class="model-info-row"><strong>{{ model.name }}</strong><span>{{ model.information.model_type }}</span><span>{{ model.information.purpose }}</span><span>{{ model.information.framework ?? '—' }}</span><span>{{ model.information.input_dimensions ?? '—' }}</span><span>{{ model.information.output_dimensions ?? '—' }}</span></div><div v-for="bundle in stats.models?.filter((item) => item.load?.shared_bundle)" :key="`${bundle.name}-bundle`" class="model-info-row"><strong>{{ bundle.name }}</strong><span>{{ bundle.information.models_included }}</span><span>RAM Δ {{ bundle.load?.process_rss_delta_mb ?? '—' }} MB</span><span>VRAM Δ {{ bundle.load?.device_vram_delta_mb ?? '—' }} MB</span></div></details>
    </section>
    <div class="toolbar"><input v-model="query" placeholder="Search ID or name" @input="refresh"><span>{{ students.length }} students</span></div>
    <div class="table-wrap"><table><thead><tr><th>Face</th><th>Student</th><th>Embeddings</th><th>Last updated</th><th>Actions</th></tr></thead><tbody><tr v-for="student in students" :key="student.student_id"><td><img v-if="student.image_url" :src="imageUrl(student)" class="avatar"><span v-else>—</span></td><td><strong>{{ student.name }}</strong><small>{{ student.student_id }}</small></td><td>{{ student.embedding_count }}</td><td>{{ student.last_updated ? new Date(student.last_updated).toLocaleString() : '—' }}</td><td><button type="button" class="btn ghost update" :disabled="busy === student.student_id" @click="chooseUpdate(student)">Update face</button><button type="button" class="btn danger" :disabled="busy === student.student_id" @click="remove(student)">Delete</button></td></tr><tr v-if="!students.length"><td colspan="5">No students found.</td></tr></tbody></table></div>
  </div>
</template>
<style scoped>
.page{width:100%;max-width:1480px;margin:auto}.intro{margin-bottom:25px}.eyebrow{font:0.72rem var(--font-mono);letter-spacing:.08em;text-transform:uppercase;color:var(--accent)}h1,h2{font-family:var(--font-display);margin:8px 0}.lede,small,.toolbar{color:var(--text-muted)}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:24px}.stats div{background:var(--panel);border:1px solid var(--border-soft);padding:14px;border-radius:var(--radius-md)}.stats span{display:block;color:var(--text-muted);font-size:.72rem}.stats strong{display:block;margin-top:6px;font-family:var(--font-mono);font-size:.88rem}.model-performance{margin:0 0 24px}.section-heading{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:10px}.section-heading small{max-width:430px}.performance-summary{display:flex;gap:22px;flex-wrap:wrap;margin:0 0 12px;color:var(--text-muted);font-size:.8rem}.performance-summary strong{color:var(--text-primary);font-family:var(--font-mono);margin-left:4px}.model-info{margin-top:10px;color:var(--text-muted);font-size:.8rem}.model-info summary{cursor:pointer;color:var(--accent)}.model-info-row{display:flex;gap:12px;flex-wrap:wrap;padding:10px 0;border-bottom:1px solid var(--border-soft)}.model-info-row strong{color:var(--text-primary)}.toolbar{display:flex;justify-content:space-between;margin:12px 0}.toolbar input{padding:10px;background:var(--panel);border:1px solid var(--border-soft);border-radius:var(--radius-sm);color:var(--text-primary)}.table-wrap{overflow:auto;border:1px solid var(--border-soft);border-radius:var(--radius-md)}table{width:100%;border-collapse:collapse}th,td{padding:12px;text-align:left;border-bottom:1px solid var(--border-soft);white-space:nowrap}th{font-size:.72rem;text-transform:uppercase;color:var(--text-muted)}td strong,td small{display:block}.avatar{height:40px;width:40px;border-radius:50%;object-fit:cover}.btn{margin-right:6px;padding:7px 10px}.update{border-color:var(--accent);color:var(--accent);cursor:pointer}.update:hover:not(:disabled){background:var(--accent-dim)}.danger{border-color:var(--danger);color:var(--danger)}@media(max-width:700px){.stats{grid-template-columns:repeat(2,1fr)}.section-heading{display:block}}
</style>
